version: '3'
services:
  app:
    image: dockerlab
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/springbootdb
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATA_MONGODB_URI: mongodb+srv://root:root@cluster0.baloz.mongodb.net/docker?retryWrites=true&w=majority
    depends_on:
#      - db
      - mongo

#  db:
#    image: mysql:8.0
#    environment:
#      MYSQL_DATABASE: springbootdb
#      MYSQL_ROOT_PASSWORD: root
#    ports:
#      - "3307:3306"
#    volumes:
#      - db_data:/var/lib/mysql

  mongo:
    image: mongo:4.4
    environment:

      MONGO_INITDB_DATABASE: docker
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
#  db_data:
  mongo_data:
